version: '3'
services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  network_mode: host
